apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace onde tudo vai rodar
namespace: machine-learning-ecar

# Puxa todos os recursos definidos em base/
resources:
  - ../../base

# Se tiver patches, liste-os aqui
patchesStrategicMerge:
  - patches.yaml   # arquivo de patch com ajustes para produção
