apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml

# Gera um ConfigMap “frontend-nginx-conf” com o default.conf
configMapGenerator:
  - name: frontend-nginx-conf
    files:
      - default.conf=frontend-default.conf
