apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml

configMapGenerator:
  - name: frontend-nginx-config
    files:
      - default.conf=frontend-default.conf
